/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module BIn2Dec_8bits (
  input IN7,
  input IN6,
  input IN5,
  input IN4,
  input IN3,
  input IN2,
  input IN1,
  input IN0,
  output C1,
  output C0,
  output D3,
  output D2,
  output D1,
  output D0,
  output U3,
  output U2,
  output U1,
  output U0
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign C1 = ((IN3 & IN6 & IN7) | (IN4 & IN6 & IN7) | (IN5 & IN6 & IN7));
  assign s0 = ~ IN7;
  assign s4 = ~ IN6;
  assign s3 = ~ IN5;
  assign s2 = ~ IN4;
  assign s1 = ~ IN3;
  assign s5 = ~ IN2;
  assign s6 = ~ IN1;
  assign C0 = ((IN2 & IN5 & IN6 & s0) | (s1 & s2 & s3 & IN7) | (IN3 & IN5 & IN6 & s0) | (IN4 & IN5 & IN6 & s0) | (s4 & IN7));
  assign D3 = ((s5 & s1 & s2 & IN5 & IN6 & s0) | (IN2 & IN4 & IN5 & s4 & IN7) | (IN3 & IN4 & IN5 & s4 & IN7) | (s1 & s2 & s3 & IN6 & IN7) | (IN4 & s3 & IN6 & s0));
  assign D2 = ((s5 & s1 & IN4 & IN5 & s4) | (IN2 & IN3 & s2 & s4 & IN7) | (IN3 & s2 & IN5 & s4) | (IN4 & IN5 & s4 & s0) | (s2 & s3 & IN6 & s0) | (IN4 & s3 & s4 & IN7) | (s2 & IN5 & s4 & IN7) | (IN4 & IN5 & IN6 & IN7));
  assign D1 = ((IN2 & IN3 & IN4 & s3 & IN6 & IN7) | (IN2 & IN3 & IN4 & IN5 & s0) | (s5 & s1 & IN5 & s4 & IN7) | (IN2 & IN4 & s3 & s4 & s0) | (s5 & s2 & s4 & IN7) | (IN3 & IN4 & s3 & s4 & s0) | (IN3 & IN4 & IN5 & IN6 & s0) | (s1 & s2 & IN5 & s4) | (s1 & s2 & s4 & IN7) | (s2 & s3 & IN6 & s0) | (s2 & IN5 & IN7));
  assign D0 = ((IN1 & s5 & s1 & s2 & s3 & IN7) | (s6 & IN2 & s1 & s2 & s3 & IN7) | (IN1 & IN2 & s1 & IN4 & s3 & IN7) | (IN1 & s5 & IN3 & s2 & s3 & s4) | (IN1 & IN2 & IN3 & IN4 & s3 & s4) | (IN1 & s5 & s1 & IN4 & IN5 & s4) | (IN1 & s5 & IN3 & IN4 & s3 & IN6) | (IN1 & IN2 & IN3 & s2 & IN5 & IN6) | (IN1 & s5 & IN3 & s2 & s4 & IN7) | (IN1 & IN2 & IN3 & IN4 & s4 & IN7) | (IN1 & s5 & IN3 & IN4 & IN6 & IN7) | (IN1 & IN2 & s1 & s3 & s4 & IN7) | (IN1 & s5 & s1 & s3 & IN6 & IN7) | (s6 & IN2 & s1 & s3 & IN6 & IN7) | (IN1 & IN2 & s2 & s3 & IN6 & s0) | (IN1 & IN2 & s2 & IN5 & IN6 & IN7) | (s6 & s1 & s2 & s3 & IN6 & IN7) | (s5 & s1 & s2 & IN5 & s0) | (IN2 & s1 & IN4 & IN5 & s0) | (s5 & s1 & IN4 & s3 & s4 & s0) | (s5 & IN3 & IN4 & IN5 & s4 & s0) | (s5 & s1 & IN4 & IN5 & s4 & IN7) | (IN2 & IN3 & s2 & s3 & s0) | (s5 & IN3 & IN4 & s3 & IN7) | (IN2 & IN3 & s2 & IN5 & IN7) | (IN2 & s1 & IN5 & s4 & s0) | (IN2 & IN3 & s3 & IN6 & s0) | (s5 & s1 & IN5 & IN6 & s0) | (s5 & IN3 & s3 & s4 & IN7) | (IN2 & IN3 & IN5 & IN6 & IN7) | (IN3 & s2 & s3 & IN6 & s0) | (IN3 & IN4 & s3 & s4 & IN7) | (IN3 & s2 & IN5 & IN6 & IN7));
  assign U3 = ((s6 & s5 & IN3 & s2 & s3 & s4 & s0) | (IN1 & s5 & s1 & IN4 & s3 & s4 & s0) | (s6 & IN2 & IN3 & IN4 & s3 & s4 & s0) | (IN1 & IN2 & s1 & s2 & IN5 & s4 & s0) | (s6 & s5 & s1 & IN4 & IN5 & s4 & s0) | (IN1 & s5 & IN3 & IN4 & IN5 & s4 & s0) | (s6 & IN2 & s1 & s2 & s3 & IN6 & s0) | (IN1 & IN2 & IN3 & s2 & s3 & IN6 & s0) | (s6 & s5 & IN3 & IN4 & s3 & IN6 & s0) | (IN1 & s5 & s1 & s2 & IN5 & IN6 & s0) | (s6 & IN2 & IN3 & s2 & IN5 & IN6 & s0) | (IN1 & IN2 & s1 & IN4 & IN5 & IN6 & s0) | (s6 & s5 & s1 & s2 & s3 & s4 & IN7) | (IN1 & s5 & IN3 & s2 & s3 & s4 & IN7) | (s6 & IN2 & s1 & IN4 & s3 & s4 & IN7) | (IN1 & IN2 & IN3 & IN4 & s3 & s4 & IN7) | (s6 & s5 & IN3 & s2 & IN5 & s4 & IN7) | (IN1 & s5 & s1 & IN4 & IN5 & s4 & IN7) | (s6 & IN2 & IN3 & IN4 & IN5 & s4 & IN7) | (IN1 & IN2 & s1 & s2 & s3 & IN6 & IN7) | (s6 & s5 & s1 & IN4 & s3 & IN6 & IN7) | (IN1 & s5 & IN3 & IN4 & s3 & IN6 & IN7) | (s6 & IN2 & s1 & s2 & IN5 & IN6 & IN7) | (IN1 & IN2 & IN3 & s2 & IN5 & IN6 & IN7) | (s6 & s5 & IN3 & IN4 & IN5 & IN6 & IN7));
  assign U2 = ((IN1 & IN2 & s1 & s2 & s3 & s4) | (s6 & s5 & s1 & IN4 & s3 & s4) | (IN1 & s5 & IN3 & IN4 & s3 & s4) | (s6 & IN2 & s1 & s2 & IN5 & s4) | (IN1 & IN2 & IN3 & s2 & IN5 & s4) | (s6 & s5 & IN3 & IN4 & IN5 & s4) | (IN1 & s5 & s1 & s2 & s3 & IN6) | (IN1 & IN2 & s1 & IN4 & s3 & IN6) | (s6 & s5 & s1 & s2 & IN5 & IN6) | (IN1 & s5 & IN3 & s2 & IN5 & IN6) | (s6 & IN2 & s1 & IN4 & IN5 & IN6) | (IN1 & IN2 & IN3 & IN4 & IN5 & IN6) | (IN1 & s5 & s1 & s2 & IN5 & s4 & s0) | (IN1 & IN2 & s1 & IN4 & IN5 & s4 & s0) | (IN1 & s5 & s1 & IN4 & IN5 & IN6 & s0) | (s6 & s5 & IN3 & s2 & s3 & s4 & IN7) | (s6 & IN2 & IN3 & IN4 & s3 & s4 & IN7) | (s6 & s5 & IN3 & IN4 & s3 & IN6 & IN7) | (s6 & IN2 & IN3 & s2 & s3 & IN6) | (s6 & IN2 & s1 & s2 & s4 & s0) | (IN1 & IN2 & IN3 & s2 & s4 & s0) | (s6 & s5 & IN3 & IN4 & s4 & s0) | (s6 & s5 & s1 & s2 & IN6 & s0) | (IN1 & s5 & IN3 & s2 & IN6 & s0) | (s6 & IN2 & s1 & IN4 & IN6 & s0) | (IN1 & IN2 & IN3 & IN4 & IN6 & s0) | (IN1 & IN2 & s1 & s2 & s4 & IN7) | (s6 & s5 & s1 & IN4 & s4 & IN7) | (IN1 & s5 & IN3 & IN4 & s4 & IN7) | (IN1 & s5 & s1 & s2 & IN6 & IN7) | (s6 & IN2 & IN3 & s2 & IN6 & IN7) | (IN1 & IN2 & s1 & IN4 & IN6 & IN7) | (s6 & IN2 & s2 & IN5 & s4 & s0) | (s6 & s5 & s2 & IN5 & IN6 & s0) | (s6 & IN2 & IN4 & IN5 & IN6 & s0) | (IN1 & s5 & IN4 & s3 & s4 & IN7) | (s6 & IN2 & s2 & s3 & IN6 & IN7) | (IN2 & IN3 & s2 & s3 & IN6 & IN7));
  assign U1 = ((IN1 & s5 & s1 & s2 & s3 & s0) | (IN1 & IN2 & s1 & IN4 & s3 & s0) | (s6 & s5 & s1 & s2 & IN5 & s0) | (IN1 & s5 & IN3 & s2 & IN5 & s0) | (s6 & IN2 & s1 & IN4 & IN5 & s0) | (IN1 & IN2 & IN3 & IN4 & IN5 & s0) | (IN1 & s5 & s1 & s2 & IN5 & IN7) | (IN1 & IN2 & s1 & IN4 & IN5 & IN7) | (s6 & s5 & s1 & IN4 & s3 & s4 & s0) | (IN1 & s5 & IN3 & IN4 & s3 & s4 & s0) | (s6 & s5 & IN3 & IN4 & IN5 & s4 & s0) | (IN1 & IN2 & s1 & s2 & IN5 & IN6 & s0) | (IN1 & s5 & s1 & IN4 & s3 & s4 & IN7) | (s6 & s5 & s1 & IN4 & IN5 & s4 & IN7) | (IN1 & s5 & IN3 & IN4 & IN5 & s4 & IN7) | (s6 & IN2 & IN3 & s2 & s3 & s0) | (s6 & IN2 & s1 & s2 & s3 & IN7) | (IN1 & IN2 & IN3 & s2 & s3 & IN7) | (s6 & s5 & IN3 & IN4 & s3 & IN7) | (s6 & IN2 & IN3 & s2 & IN5 & IN7) | (IN1 & IN2 & s1 & s3 & s4 & s0) | (s6 & IN2 & s1 & IN5 & s4 & s0) | (IN1 & IN2 & IN3 & IN5 & s4 & s0) | (IN1 & s5 & s1 & s3 & IN6 & s0) | (s6 & IN2 & IN3 & s3 & IN6 & s0) | (s6 & s5 & s1 & IN5 & IN6 & s0) | (IN1 & s5 & IN3 & IN5 & IN6 & s0) | (s6 & s5 & IN3 & s3 & s4 & IN7) | (IN1 & IN2 & s1 & IN5 & s4 & IN7) | (s6 & IN2 & s1 & s3 & IN6 & IN7) | (IN1 & IN2 & IN3 & s3 & IN6 & IN7) | (IN1 & s5 & s1 & IN5 & IN6 & IN7) | (s6 & IN2 & IN3 & IN5 & IN6 & IN7) | (s6 & IN3 & s2 & s3 & IN6 & s0) | (s6 & IN3 & IN4 & s3 & s4 & IN7) | (s6 & s1 & s2 & s3 & IN6 & IN7) | (IN1 & IN3 & s2 & s3 & IN6 & IN7) | (s6 & IN3 & s2 & IN5 & IN6 & IN7));
  assign U0 = IN0;
endmodule

module \Bin.Dec27seg  (
  input IA,
  input IB,
  input IC,
  input ID,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s0 = ~ IA;
  assign s1 = ~ IB;
  assign s2 = ~ IC;
  assign s3 = ~ ID;
  assign a = ((s0 & IB & ID) | (IA & s1 & s2) | (s0 & IC & ID) | (s0 & s1 & s3));
  assign b = ((s0 & s1) | (s0 & s2 & s3) | (s0 & IC & ID) | (s1 & s2));
  assign c = ((s0 & ID) | (s0 & IB) | (s1 & s2));
  assign d = ((s0 & s1 & IC) | (s0 & IB & s2 & ID) | (s0 & IC & s3) | (s1 & s2 & s3));
  assign e = ((s0 & IC & s3) | (s1 & s2 & s3));
  assign f = ((s0 & IB & s2) | (s0 & IB & s3) | (IA & s1 & s2) | (s1 & s2 & s3));
  assign g = ((s0 & s1 & IC) | (s0 & IB & s2) | (IA & s1 & s2) | (s0 & IC & s3));
endmodule

module \8bit_2_7Seg  (
  input A0,
  input A1,
  input A2,
  input A3,
  input A4,
  input A5,
  input A6,
  input A7,
  input \0 ,
  output Ca,
  output Cb,
  output Cc,
  output Cd,
  output Ce,
  output Cf,
  output Cg,
  output Da,
  output Db,
  output Dc,
  output Dd,
  output De,
  output Df,
  output Dg,
  output Ua,
  output Ub,
  output Uc,
  output Ud,
  output Ue,
  output Uf,
  output Ug
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  BIn2Dec_8bits BIn2Dec_8bits_i0 (
    .IN7( A7 ),
    .IN6( A6 ),
    .IN5( A5 ),
    .IN4( A4 ),
    .IN3( A3 ),
    .IN2( A2 ),
    .IN1( A1 ),
    .IN0( A0 ),
    .C1( s0 ),
    .C0( s1 ),
    .D3( s2 ),
    .D2( s3 ),
    .D1( s4 ),
    .D0( s5 ),
    .U3( s6 ),
    .U2( s7 ),
    .U1( s8 ),
    .U0( s9 )
  );
  \Bin.Dec27seg  \Bin.Dec27seg_i1 (
    .IA( s6 ),
    .IB( s7 ),
    .IC( s8 ),
    .ID( s9 ),
    .a( Ua ),
    .b( Ub ),
    .c( Uc ),
    .d( Ud ),
    .e( Ue ),
    .f( Uf ),
    .g( Ug )
  );
  \Bin.Dec27seg  \Bin.Dec27seg_i2 (
    .IA( s2 ),
    .IB( s3 ),
    .IC( s4 ),
    .ID( s5 ),
    .a( Da ),
    .b( Db ),
    .c( Dc ),
    .d( Dd ),
    .e( De ),
    .f( Df ),
    .g( Dg )
  );
  \Bin.Dec27seg  \Bin.Dec27seg_i3 (
    .IA( \0  ),
    .IB( \0  ),
    .IC( s0 ),
    .ID( s1 ),
    .a( Ca ),
    .b( Cb ),
    .c( Cc ),
    .d( Cd ),
    .e( Ce ),
    .f( Cf ),
    .g( Cg )
  );
endmodule
